/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IInterpreterCallerConsumer } from "./IInterpreterCallerConsumer";
export type { IInterpreterV1Consumer } from "./IInterpreterV1Consumer";
