/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IInterpreterCallerConsumer__factory } from "./IInterpreterCallerConsumer__factory";
export { IInterpreterV1Consumer__factory } from "./IInterpreterV1Consumer__factory";
