/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICloneableFactoryV1 } from "./ICloneableFactoryV1";
export type { ICloneableV1 } from "./ICloneableV1";
