/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICloneableFactoryV1__factory } from "./ICloneableFactoryV1__factory";
export { ICloneableV1__factory } from "./ICloneableV1__factory";
