/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as concrete from "./concrete";
export type { concrete };
import type * as interface from "./interface";
export type { interface };
