name: CI Deploy

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["CI Test"]
    types:
      - completed

env:
  THE_GRAPH_API_TOKEN: ${{ secrets.THE_GRAPH_API_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Graph Authentication
        run: npx graph auth --product hosted-service $THE_GRAPH_API_TOKEN

      - name: Prepare subgraph manifest
        run: npx mustache config/mumbai.json subgraph.template.yaml subgraph.yaml

      - name: Graph Deployments
        run: npx graph deploy --product hosted-service rainprotocol/interpreter-registry
