name: CI Deploy

on:
  workflow_run:
    workflows: ["CI Test"]
    types:
      - completed

env:
  THE_GRAPH_API_TOKEN: ${{ secrets.THE_GRAPH_API_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Prepare subgraph manifest
        run: nix-shell --run prepare-deploy-ci

      - name: Graph Authentication
        run: npx graph auth --product hosted-service $THE_GRAPH_API_TOKEN

      - name: Graph Deployments
        run: npx graph deploy --product hosted-service rainprotocol/interpreter-registry
