name: Interpreter Subgraph  CI
on: [push]
env:
  THE_GRAPH_API_TOKEN: ${{ secrets.THE_GRAPH_API_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build Docker Compose images
        run: |
          nix-shell --run graph-node-down
          nix-shell --run graph-node-up

      - name: Run Subgraph tests
        run: nix-shell --run graph-test

      - name: Stop containers
        run: nix-shell --run graph-node-down

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      # Mumbai sg
      - name: Prepare subgraph manifest
        run: nix-shell --run prepare-deploy-ci-mumbai
      - name: Graph Authentication
        run: npx graph auth --product hosted-service $THE_GRAPH_API_TOKEN
      - name: Graph Deployments
        run: npx graph deploy --product hosted-service rainprotocol/interpreter-registry
      # Polygon sg
      - name: Prepare subgraph manifest
        run: nix-shell --run prepare-deploy-ci-polygon
      - name: Graph Authentication
        run: npx graph auth --product hosted-service $THE_GRAPH_API_TOKEN
      - name: Graph Deployments
        run: npx graph deploy --product hosted-service rainprotocol/interpreter-registry-polygon
