name: CI Test
on: [push]

env:
  THE_GRAPH_API_TOKEN: ${{ secrets.THE_GRAPH_API_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build Docker Compose images
        run: |
          nix-shell --run graph-node-down
          nix-shell --run graph-node-up

      - name: Run Subgraph tests
        run: nix-shell --run graph-test

      - name: Stop containers
        run: nix-shell --run graph-node-down
